/root/
    /domu/
        index.html
    /basic/
        index.html
    /cart/
        index.html
    /kontakt/
        index.html
    /cookies/
        index.html
    /error/
        index.html
    /produkty/
        index.html
        /dactenergy/
            index.html
    /o-nas/
        index.html